### ISSUE TITLE
Github bot Authentication

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping-chat-bots#48]
Reminder to not forget to add an unlimited API key for the Github bot after we launch the real limits

**Comment by jimaek** [comment]
@MartinKolarik We need to do for Github the same as we did for Slack. Currently my part of the system simply takes the nonfictions and calls https://github.com/jsdelivr/globalping-chat-bots/blob/master/packages/slack/src/github/handler.ts

Any ideas? Maybe since we have the github usernames we could automatically apply their limits to Github bot calls

**Comment by MartinKolarik** [comment]
We'll give the bot a special personal token. Please update it to read it from `GLOBALPING_TOKEN` and send it with the requests if set.

**Comment by MartinKolarik** [comment]
Assigning to myself to actually add the token.
