### ISSUE TITLE
Resolve eslint warnings

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-chat-bots#64]
I added ignore rules for some less important, the rest needs to be resolved. After that, I'll change the lint command to report warnings as errors. Also two TODOs like this:
```
// TODO add the actual type
```

**Comment by MartinKolarik** [comment]
@radulucut good time to do this.

**Comment by radulucut** [comment]
There are no warnings left.
I'm not sure what you mean by `add the actual type`, the conversion/parsing is done because the current version of mysql driver does not convert the json type by default.

**Comment by MartinKolarik** [comment]
Yes, you need to parse/stringify manually, but it shouldn't result in bypassing the type system; I've put `never` there, but it should stay as a string on inserts. On selects, you read that string, parse, and return whatever new type is correct. [This](https://github.com/jsdelivr/globalping-chat-bots/blob/a89d3d415bac66d5a2246275373a0d1debd7d561/packages/slack/src/db.ts#L32) is wrong because the DB doesn't return `AuthorizeSession`, it only returns a string, and the wrong type there forces you to do weird typecasting to work around that like here https://github.com/jsdelivr/globalping-chat-bots/blob/a89d3d415bac66d5a2246275373a0d1debd7d561/packages/slack/src/db.ts#L244
