### ISSUE TITLE
Create js client for the API

### ISSUE THREAD

**Issue by radulucut** [jsdelivr/globalping-chat-bots#66]
I think that it might be a good idea to have a separate js client for the [Globalping API](https://globalping.io/docs/api.globalping.io), published to a registry like npm, so we can re-use it across all services (and also to be used by others).

**Comment by jimaek** [comment]
FYI there is this https://github.com/eyepokes/globalping-ts we could potentially use

**Comment by radulucut** [comment]
You should probably own the repo and the package, for security reasons and to be able to update it as the api changes.
There is no license on that repo btw.

**Comment by MartinKolarik** [comment]
We have a task for it at https://github.com/jsdelivr/globalping/issues/195. We should definitely have an official client, just didn't get around to it yet. For now, you can share whatever is needed across the bots here at least since it's a monorepo.
